config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      patch :suspend
      patch :activate
    end
  end

  resources :records do
    member do
      patch :verify
      patch :object
    end
  end

  resources :permissions
  resources :circles
  resources :branches

  resources :documents, only: [] do
    collection do
      # post :verify
      get :verify, as: 'verify'
    end
    member do
      get :download
    end
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">User Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Dashboard', root_path, class: 'nav-link' %>
        </li>

        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Manage Users', users_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Manage Permissions', permissions_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Manage Circles', circles_path, class: 'nav-link' %>
          </li>
        <% end %>

        <% if current_user.admin? || current_user.circle_admin? %>
          <li class="nav-item">
            <%= link_to 'Manage Branches', branches_path, class: 'nav-link' %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to 'Manage Records', records_path, class: 'nav-link' %>
        </li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown">
            <%= current_user.full_name %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><span class="dropdown-item-text"><%= current_user.role.titleize %></span></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= button_to 'Log Out', logout_path, method: :delete, class: 'dropdown-item' %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Management System</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render 'layouts/navigation' if logged_in? %>

<div class="container mt-4">
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>